var Resource=require("./resource.js");
function Turtle(a){this.sensory={map:0,signalStrength:0,colorRed:0,colorGreen:0,colorBlue:0,colorClear:0,floor:0,accelerationX:0,accelerationY:0,accelerationZ:0,temperature:0,button:0,colorNumber:-1,colorPattern:-1,pulseCount:0,tilt:0,wheelState:0,soundState:0,lineTracerState:0,batteryState:2};this.motoring={module:"turtle",index:a,map:4160749568,leftWheel:0,rightWheel:0,ledRed:0,ledGreen:0,ledBlue:0,buzzer:0,pulse:0,note:0,sound:0,lineTracerMode:0,lineTracerGain:5,lineTracerSpeed:5,lamp:1,lock:0,
motionType:0,motionUnit:0,motionSpeed:0,motionValue:0,motionRadius:0};this.blockId=0;this.lineTracerCallback=this.motionCallback=void 0;this.currentSound=0;this.soundRepeat=1;this.soundCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=void 0;this.longPressed=this.doubleClicked=this.clicked=!1;this.colorPattern=-1;this.tempo=60;this.timeouts=[]}
Turtle.prototype.reset=function(){var a=this.motoring;a.map=4293132288;a.leftWheel=0;a.rightWheel=0;a.ledRed=0;a.ledGreen=0;a.ledBlue=0;a.buzzer=0;a.pulse=0;a.note=0;a.sound=0;a.lineTracerMode=0;a.lineTracerGain=5;a.lineTracerSpeed=5;a.lamp=1;a.lock=0;a.motionType=0;a.motionUnit=0;a.motionSpeed=0;a.motionValue=0;this.blockId=a.motionRadius=0;this.lineTracerCallback=this.motionCallback=void 0;this.currentSound=0;this.soundRepeat=1;this.soundCallback=void 0;this.noteId=0;this.noteTimer2=this.noteTimer1=
void 0;this.longPressed=this.doubleClicked=this.clicked=!1;this.colorPattern=-1;this.tempo=60;this.__removeAllTimeouts()};Turtle.prototype.__removeTimeout=function(a){clearTimeout(a);a=this.timeouts.indexOf(a);0<=a&&this.timeouts.splice(a,1)};Turtle.prototype.__removeAllTimeouts=function(){var a=this.timeouts,b;for(b in a)clearTimeout(a[b]);this.timeouts=[]};Turtle.prototype.clearMotoring=function(){this.motoring.map=4160749568};
Turtle.prototype.clearEvent=function(){this.longPressed=this.doubleClicked=this.clicked=!1;this.colorPattern=-1};Turtle.prototype.__setPulse=function(a){this.motoring.pulse=a;this.motoring.map|=67108864};Turtle.prototype.__setLineTracerMode=function(a){this.motoring.lineTracerMode=a;this.motoring.map|=8388608};Turtle.prototype.__setLineTracerGain=function(a){this.motoring.lineTracerGain=a;this.motoring.map|=4194304};
Turtle.prototype.__setLineTracerSpeed=function(a){this.motoring.lineTracerSpeed=a;this.motoring.map|=2097152};Turtle.prototype.__cancelLineTracer=function(){this.lineTracerCallback=void 0};Turtle.prototype.__setMotion=function(a,b,c,d,e){var f=this.motoring;f.motionType=a;f.motionUnit=b;f.motionSpeed=c;f.motionValue=d;f.motionRadius=e;f.map|=262144};Turtle.prototype.__cancelMotion=function(){this.motionCallback=void 0};
Turtle.prototype.__setNote=function(a){this.motoring.note=a;this.motoring.map|=33554432};Turtle.prototype.__issueNoteId=function(){return this.noteId=this.blockId=this.blockId%65535+1};Turtle.prototype.__cancelNote=function(){this.noteId=0;void 0!==this.noteTimer1&&this.__removeTimeout(this.noteTimer1);void 0!==this.noteTimer2&&this.__removeTimeout(this.noteTimer2);this.noteTimer2=this.noteTimer1=void 0};Turtle.prototype.__setSound=function(a){this.motoring.sound=a;this.motoring.map|=16777216};
Turtle.prototype.__runSound=function(a,b){"number"!=typeof b&&(b=1);0>b&&(b=-1);b&&(this.currentSound=a,this.soundRepeat=b,this.__setSound(a))};Turtle.prototype.__cancelSound=function(){this.soundCallback=void 0};
Turtle.prototype.handleSensory=function(){var a=this.sensory;a.map&2048&&(this.clicked=!0);a.map&1024&&(this.doubleClicked=!0);a.map&512&&(this.longPressed=!0);a.map&128&&(this.colorPattern=a.colorPattern);if(this.lineTracerCallback&&0!=(a.map&8)&&2==a.lineTracerState){this.__setLineTracerMode(0);var b=this.lineTracerCallback;this.__cancelLineTracer();b&&b()}this.motionCallback&&0!=(a.map&32)&&0==a.wheelState&&(this.motoring.leftWheel=0,this.motoring.rightWheel=0,b=this.motionCallback,this.__cancelMotion(),
b&&b());0!=(a.map&16)&&0==a.soundState&&(0<this.currentSound?0>this.soundRepeat?this.__runSound(this.currentSound,-1):1<this.soundRepeat?(this.soundRepeat--,this.__runSound(this.currentSound,this.soundRepeat)):(this.currentSound=0,this.soundRepeat=1,a=this.soundCallback,this.__cancelSound(),a&&a()):(this.currentSound=0,this.soundRepeat=1,a=this.soundCallback,this.__cancelSound(),a&&a()))};Turtle.prototype.__UNITS={cm:1,degrees:1,seconds:2,pulses:3};
Turtle.prototype.__motion=function(a,b){var c=this.motoring;this.__cancelLineTracer();c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(a,1,0,0,0);this.motionCallback=b;this.__setLineTracerMode(0)};
Turtle.prototype.__motionUnit=function(a,b,c,d){var e=this.motoring;this.__cancelLineTracer();this.__cancelMotion();e.leftWheel=0;e.rightWheel=0;this.__setPulse(0);(c=parseFloat(c))&&0<c?(this.__setMotion(a,b,0,c,0),this.motionCallback=d,this.__setLineTracerMode(0)):(this.__setMotion(0,0,0,0,0),this.__setLineTracerMode(0),d())};
Turtle.prototype.__motionUnitRadius=function(a,b,c,d,e){var f=this.motoring;this.__cancelLineTracer();this.__cancelMotion();f.leftWheel=0;f.rightWheel=0;this.__setPulse(0);c=parseFloat(c);d=parseFloat(d);c&&0<c&&"number"==typeof d&&0<=d?(this.__setMotion(a,b,0,c,d),this.motionCallback=e,this.__setLineTracerMode(0)):(this.__setMotion(0,0,0,0,0),this.__setLineTracerMode(0),e())};Turtle.prototype.moveForward=function(a){this.__motion(101,a)};
Turtle.prototype.moveBackward=function(a){this.__motion(102,a)};Turtle.prototype.turn=function(a,b){"left"==a?this.__motion(103,b):this.__motion(104,b)};Turtle.prototype.moveForwardUnit=function(a,b,c){0>a?this.__motionUnit(2,this.__UNITS[b],-a,c):this.__motionUnit(1,this.__UNITS[b],a,c)};Turtle.prototype.moveBackwardUnit=function(a,b,c){0>a?this.__motionUnit(1,this.__UNITS[b],-a,c):this.__motionUnit(2,this.__UNITS[b],a,c)};
Turtle.prototype.turnUnit=function(a,b,c,d){"left"==a?0>b?this.__motionUnit(4,this.__UNITS[c],-b,d):this.__motionUnit(3,this.__UNITS[c],b,d):0>b?this.__motionUnit(3,this.__UNITS[c],-b,d):this.__motionUnit(4,this.__UNITS[c],b,d)};
Turtle.prototype.pivotUnit=function(a,b,c,d,e){c=this.__UNITS[c];"left"==a?"head"==d?0>b?this.__motionUnit(6,c,-b,e):this.__motionUnit(5,c,b,e):0>b?this.__motionUnit(5,c,-b,e):this.__motionUnit(6,c,b,e):"head"==d?0>b?this.__motionUnit(8,c,-b,e):this.__motionUnit(7,c,b,e):0>b?this.__motionUnit(7,c,-b,e):this.__motionUnit(8,c,b,e)};
Turtle.prototype.swingUnit=function(a,b,c,d,e,f){c=this.__UNITS[c];"left"==a?"head"==e?0>b?this.__motionUnitRadius(10,c,-b,d,f):this.__motionUnitRadius(9,c,b,d,f):0>b?this.__motionUnitRadius(9,c,-b,d,f):this.__motionUnitRadius(10,c,b,d,f):"head"==e?0>b?this.__motionUnitRadius(12,c,-b,d,f):this.__motionUnitRadius(11,c,b,d,f):0>b?this.__motionUnitRadius(11,c,-b,d,f):this.__motionUnitRadius(12,c,b,d,f)};
Turtle.prototype.setWheels=function(a,b){var c=this.motoring;this.__cancelLineTracer();this.__cancelMotion();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel=a);"number"==typeof b&&(c.rightWheel=b);this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
Turtle.prototype.changeWheels=function(a,b){var c=this.motoring;this.__cancelLineTracer();this.__cancelMotion();a=parseFloat(a);b=parseFloat(b);"number"==typeof a&&(c.leftWheel+=a);"number"==typeof b&&(c.rightWheel+=b);this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
Turtle.prototype.setWheel=function(a,b){var c=this.motoring;this.__cancelLineTracer();this.__cancelMotion();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel=b:("right"!=a&&(c.leftWheel=b),c.rightWheel=b));this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};
Turtle.prototype.changeWheel=function(a,b){var c=this.motoring;this.__cancelLineTracer();this.__cancelMotion();b=parseFloat(b);"number"==typeof b&&("left"==a?c.leftWheel+=b:("right"!=a&&(c.leftWheel+=b),c.rightWheel+=b));this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};Turtle.prototype.__LINE_COLORS={black:0,red:1,yellow:2,green:3,"sky blue":4,blue:5,purple:6,"any color":7};
Turtle.prototype.followLine=function(a){var b=this.motoring;this.__cancelLineTracer();this.__cancelMotion();a=10+this.__LINE_COLORS[a];b.leftWheel=0;b.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(a)};Turtle.prototype.followLineUntil=function(a,b){var c=this.motoring;this.__cancelMotion();var d=60+this.__LINE_COLORS[a];c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(d);this.lineTracerCallback=b};
Turtle.prototype.followLineUntilBlack=function(a,b){var c=this.motoring;this.__cancelMotion();var d=70+this.__LINE_COLORS[a];c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(d);this.lineTracerCallback=b};Turtle.prototype.crossIntersection=function(a){var b=this.motoring;this.__cancelMotion();b.leftWheel=0;b.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(40);this.lineTracerCallback=a};
Turtle.prototype.turnAtIntersection=function(a,b){var c=this.motoring;this.__cancelMotion();var d=20;"right"==a?d=30:"back"==a&&(d=50);c.leftWheel=0;c.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(d);this.lineTracerCallback=b};Turtle.prototype.setLineTracerSpeed=function(a){a=parseInt(a);"number"==typeof a&&(this.__setLineTracerSpeed(a),this.__setLineTracerGain(a))};
Turtle.prototype.stop=function(){var a=this.motoring;this.__cancelLineTracer();this.__cancelMotion();a.leftWheel=0;a.rightWheel=0;this.__setPulse(0);this.__setMotion(0,0,0,0,0);this.__setLineTracerMode(0)};Turtle.prototype.__RGBS={red:[255,0,0],orange:[255,63,0],yellow:[255,255,0],green:[0,255,0],"sky blue":[0,255,255],blue:[0,0,255],violet:[63,0,255],purple:[255,0,255],white:[255,255,255]};Turtle.prototype.setHeadColor=function(a){(a=this.__RGBS[a])&&this.setHeadRgb(a[0],a[1],a[2])};
Turtle.prototype.setHeadRgbArray=function(a){a&&this.setHeadRgb(a[0],a[1],a[2])};Turtle.prototype.setHeadRgb=function(a,b,c){var d=this.motoring;a=parseInt(a);b=parseInt(b);c=parseInt(c);"number"==typeof a&&(d.ledRed=a);"number"==typeof b&&(d.ledGreen=b);"number"==typeof c&&(d.ledBlue=c)};
Turtle.prototype.changeHeadRgb=function(a,b,c){var d=this.motoring;a=parseInt(a);b=parseInt(b);c=parseInt(c);"number"==typeof a&&(d.ledRed+=a);"number"==typeof b&&(d.ledGreen+=b);"number"==typeof c&&(d.ledBlue+=c)};Turtle.prototype.clearHead=function(){this.setHeadRgb(0,0,0)};Turtle.prototype.__SOUNDS={beep:1,"random beep":2,siren:3,engine:4,robot:5,march:6,birthday:7,dibidibidip:8,"good job":9};
Turtle.prototype.playSound=function(a,b){var c=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__SOUNDS[a];b=parseInt(b);c.buzzer=0;this.__setNote(0);a&&b?this.__runSound(a,b):this.__runSound(0)};Turtle.prototype.playSoundUntil=function(a,b,c){var d=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__SOUNDS[a];b=parseInt(b);d.buzzer=0;this.__setNote(0);a&&b?(this.__runSound(a,b),this.soundCallback=c):(this.__runSound(0),c())};
Turtle.prototype.setBuzzer=function(a){var b=this.motoring;this.__cancelNote();this.__cancelSound();a=parseFloat(a);"number"==typeof a&&(b.buzzer=a);this.__setNote(0);this.__runSound(0)};Turtle.prototype.changeBuzzer=function(a){var b=this.motoring;this.__cancelNote();this.__cancelSound();a=parseFloat(a);"number"==typeof a&&(b.buzzer+=a);this.__setNote(0);this.__runSound(0)};Turtle.prototype.clearSound=function(){this.__cancelNote();this.__cancelSound();this.motoring.buzzer=0;this.__setNote(0);this.__runSound(0)};
Turtle.prototype.__NOTES={C:4,"C\u266f (D\u266d)":5,D:6,"D\u266f (E\u266d)":7,E:8,F:9,"F\u266f (G\u266d)":10,G:11,"G\u266f (A\u266d)":12,A:13,"A\u266f (B\u266d)":14,B:15};Turtle.prototype.playNote=function(a,b){var c=this.motoring;this.__cancelNote();this.__cancelSound();a=this.__NOTES[a];b=parseInt(b);c.buzzer=0;a&&b&&0<b&&8>b?this.__setNote(a+12*(b-1)):this.__setNote(0);this.__runSound(0)};
Turtle.prototype.playNoteBeat=function(a,b,c,d){var e=this,f=e.motoring;e.__cancelNote();e.__cancelSound();a=this.__NOTES[a];b=parseInt(b);c=parseFloat(c);f.buzzer=0;if(a&&b&&0<b&&8>b&&c&&0<c&&0<e.tempo){var g=e.__issueNoteId();e.__setNote(a+12*(b-1));a=6E4*c/e.tempo;b=100<a?100:0;0<b&&(e.noteTimer1=setTimeout(function(){e.noteId==g&&(e.__setNote(0),void 0!==e.noteTimer1&&e.__removeTimeout(e.noteTimer1),e.noteTimer1=void 0)},a-b),e.timeouts.push(e.noteTimer1));e.noteTimer2=setTimeout(function(){e.noteId==
g&&(e.__setNote(0),e.__cancelNote(),d())},a);e.timeouts.push(e.noteTimer2);e.__runSound(0)}else e.__setNote(0),e.__runSound(0),d()};Turtle.prototype.restBeat=function(a,b){var c=this,d=c.motoring;c.__cancelNote();c.__cancelSound();a=parseFloat(a);d.buzzer=0;c.__setNote(0);c.__runSound(0);if(a&&0<a&&0<c.tempo){var e=c.__issueNoteId();c.noteTimer1=setTimeout(function(){c.noteId==e&&(c.__cancelNote(),b())},6E4*a/c.tempo);c.timeouts.push(c.noteTimer1)}else b()};
Turtle.prototype.setTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo=a,1>this.tempo&&(this.tempo=1))};Turtle.prototype.changeTempo=function(a){a=parseFloat(a);"number"==typeof a&&(this.tempo+=a,1>this.tempo&&(this.tempo=1))};Turtle.prototype.__TOUCHING_COLORS={red:1,orange:2,yellow:3,green:4,"sky blue":5,blue:6,purple:7,black:0,white:8};Turtle.prototype.checkTouchingColor=function(a){a=this.__TOUCHING_COLORS[a];return"number"==typeof a?this.sensory.colorNumber==a:!1};
Turtle.prototype.__PATTERN_COLORS={red:1,yellow:3,green:4,"sky blue":5,blue:6,purple:7};Turtle.prototype.checkColorPattern=function(a,b){a=this.__PATTERN_COLORS[a];b=this.__PATTERN_COLORS[b];return"number"==typeof a&&"number"==typeof b?this.colorPattern==10*a+b:!1};Turtle.prototype.checkButtonEvent=function(a){return"clicked"==a?this.clicked:"double-clicked"==a?this.doubleClicked:"long-pressed"==a?this.longPressed:!1};
Turtle.prototype.checkTilt=function(a){var b=this.sensory;switch(a){case "tilt forward":return 1==b.tilt;case "tilt backward":return-1==b.tilt;case "tilt left":return 2==b.tilt;case "tilt right":return-2==b.tilt;case "tilt flip":return 3==b.tilt;case "not tilt":return-3==b.tilt}return!1};Turtle.prototype.__BATTERY_STATES={normal:2,low:1,empty:0};Turtle.prototype.checkBattery=function(a){return this.sensory.batteryState==this.__BATTERY_STATES[a]};Turtle.prototype.getColorNumber=function(){return this.sensory.colorNumber};
Turtle.prototype.getColorPattern=function(){return this.colorPattern};Turtle.prototype.getFloor=function(){return this.sensory.floor};Turtle.prototype.getButton=function(){return this.sensory.button};Turtle.prototype.getAccelerationX=function(){return this.sensory.accelerationX};Turtle.prototype.getAccelerationY=function(){return this.sensory.accelerationY};Turtle.prototype.getAccelerationZ=function(){return this.sensory.accelerationZ};
var RoboidUtil={toNumber:function(a,b){void 0===b&&(b=0);var c=Number(a);return isNaN(c)?b:c},toBoolean:function(a){return"boolean"===typeof a?a:"string"===typeof a?""===a||"0"===a||"false"===a.toLowerCase()?!1:!0:!!a},toString:function(a){return String(a)},hexToRgb:function(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(b,c,d,e){return c+c+d+d+e+e});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null},decimalToRgb:function(a){var b=
a>>24&255;return{r:a>>16&255,g:a>>8&255,b:a&255,a:0<b?b:255}},toRgbArray:function(a){a="string"===typeof a&&"#"===a.substring(0,1)?RoboidUtil.hexToRgb(a):RoboidUtil.decimalToRgb(RoboidUtil.toNumber(a));return[a.r,a.g,a.b]}},RoboidRunner=function(a){this.creators=a;this.robots={};this.robotsByGroup={};this.robotsByModule={};this.packet={};this.retryId=void 0;this.canSend=this.alive=!1};
RoboidRunner.prototype.addRobotByModule=function(a,b,c){var d=this.robotsByModule[a];void 0===d&&(d=this.robotsByModule[a]={});d[b]=c};RoboidRunner.prototype.getOrCreateRobot=function(a,b,c){var d=this.robots,e=b+c,f=d[e];if(!f){var g=this.creators[b];g&&(f=g(c));f&&(d[e]=f,this.packet[e]=f.motoring,this.addRobotByModule(b,e,f))}return this.robotsByGroup[a+c]=f};RoboidRunner.prototype.getRobot=function(a,b){return this.robotsByGroup[a+b]};
RoboidRunner.prototype.clearMotorings=function(){var a=this.robots,b;for(b in a)a[b].clearMotoring()};RoboidRunner.prototype.afterTick=function(){var a=this.robots,b;for(b in a)a[b].clearEvent()};RoboidRunner.prototype.reset=function(a){if(a=this.robotsByModule[a])for(var b in a)a[b].reset()};
RoboidRunner.prototype.open=function(){try{var a=this,b=new WebSocket("ws://localhost:56417");b.binaryType="arraybuffer";a.socket=b;b.onmessage=function(c){try{var d=JSON.parse(c.data);if(0!=d.type)if(2==d.type)for(var e in d.modules);else if(0<=d.index){var f=a.getOrCreateRobot(d.group,d.module,d.index);f&&(f.clearEvent(),f.sensory=d,f.handleSensory())}}catch(g){}};b.onclose=function(){a.alive=!1;a.canSend=!1;void 0===a.retryId&&(a.retryId=setInterval(function(){a.alive?void 0!==a.retryId&&(clearInterval(a.retryId),
a.retryId=void 0):a.open()},2E3))};b.onopen=function(){a.alive=!0;var c=Date.now(),d=function(){if(a.canSend&&a.socket){if(Date.now()>c){try{var e=JSON.stringify(a.packet);a.canSend&&a.socket&&a.socket.send(e);a.clearMotorings()}catch(f){}c+=20}setTimeout(d,5)}};a.canSend=!0;d()};return!0}catch(c){}return!1};RoboidRunner.prototype.close=function(){this.canSend=!1;this.socket&&(this.socket.close(),this.socket=void 0)};
var TurtleExtension=function(a){this.runtime=a;void 0===a.roboidCreators&&(a.roboidCreators={});a.roboidCreators.turtle=function(b){return new Turtle(b)};void 0===a.roboidRunner&&(a.roboidRunner=new RoboidRunner(a.roboidCreators),setTimeout(function(){a.roboidRunner.open()},1E3));a.registerPeripheralExtension("turtle",this);a.on("PROJECT_STOP_ALL",this.onStop.bind(this))};TurtleExtension.prototype.onStop=function(){this.runtime.roboidRunner&&this.runtime.roboidRunner.reset("turtle")};
TurtleExtension.prototype.getInfo=function(){return{id:"turtle",name:"\uac70\ubd81\uc774",color1:"#0FBD8C",color2:"#0DA57A",menuIconURI:Resource.iconURI,blockIconURI:Resource.iconURI,blocks:[{opcode:"turtleMoveForwardUnit",text:"\uc55e\uc73c\ub85c [VALUE][UNIT] \uc774\ub3d9\ud558\uae30",blockType:"command",arguments:{VALUE:{type:"number",defaultValue:6},UNIT:{type:"string",menu:"move_unit",defaultValue:"cm"}},func:"turtleMoveForwardUnit",blockCategory:"motion"},{opcode:"turtleMoveBackwardUnit",text:"\ub4a4\ub85c [VALUE][UNIT] \uc774\ub3d9\ud558\uae30",
blockType:"command",arguments:{VALUE:{type:"number",defaultValue:6},UNIT:{type:"string",menu:"move_unit",defaultValue:"cm"}},func:"turtleMoveBackwardUnit",blockCategory:"motion"},{opcode:"turtleTurnUnitInPlace",text:"[DIRECTION]\uc73c\ub85c [VALUE][UNIT] \uc81c\uc790\ub9ac \ub3cc\uae30",blockType:"command",arguments:{DIRECTION:{type:"string",menu:"left_right",defaultValue:"left"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"}},func:"turtleTurnUnitInPlace",
blockCategory:"motion"},{opcode:"turtlePivotAroundWheelUnitInDirection",text:"[WHEEL] \ubc14\ud034 \uc911\uc2ec\uc73c\ub85c [VALUE][UNIT] [TOWARD] \ubc29\ud5a5\uc73c\ub85c \ub3cc\uae30",blockType:"command",arguments:{WHEEL:{type:"string",menu:"left_right",defaultValue:"left"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"},TOWARD:{type:"string",menu:"head_tail",defaultValue:"head"}},func:"turtlePivotAroundWheelUnitInDirection",blockCategory:"motion"},
{opcode:"turtleTurnUnitWithRadiusInDirection",text:"[DIRECTION]\uc73c\ub85c [VALUE][UNIT] \ubc18\uc9c0\ub984 [RADIUS]cm\ub97c [TOWARD] \ubc29\ud5a5\uc73c\ub85c \ub3cc\uae30",blockType:"command",arguments:{DIRECTION:{type:"string",menu:"left_right",defaultValue:"left"},VALUE:{type:"number",defaultValue:90},UNIT:{type:"string",menu:"turn_unit",defaultValue:"degrees"},RADIUS:{type:"number",defaultValue:6},TOWARD:{type:"string",menu:"head_tail",defaultValue:"head"}},func:"turtleTurnUnitWithRadiusInDirection",
blockCategory:"motion"},{opcode:"turtleChangeWheelsByLeftRight",text:"\uc67c\ucabd \ubc14\ud034 [LEFT] \uc624\ub978\ucabd \ubc14\ud034 [RIGHT]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{LEFT:{type:"number",defaultValue:10},RIGHT:{type:"number",defaultValue:10}},func:"turtleChangeWheelsByLeftRight",blockCategory:"motion"},{opcode:"turtleSetWheelsToLeftRight",text:"\uc67c\ucabd \ubc14\ud034 [LEFT] \uc624\ub978\ucabd \ubc14\ud034 [RIGHT](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",
arguments:{LEFT:{type:"number",defaultValue:50},RIGHT:{type:"number",defaultValue:50}},func:"turtleSetWheelsToLeftRight",blockCategory:"motion"},{opcode:"turtleChangeWheelBy",text:"[WHEEL] \ubc14\ud034 [VALUE]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{WHEEL:{type:"string",menu:"left_right_both",defaultValue:"left"},VALUE:{type:"number",defaultValue:10}},func:"turtleChangeWheelBy",blockCategory:"motion"},{opcode:"turtleSetWheelTo",text:"[WHEEL] \ubc14\ud034 [VALUE](\uc73c)\ub85c \uc815\ud558\uae30",
blockType:"command",arguments:{WHEEL:{type:"string",menu:"left_right_both",defaultValue:"left"},VALUE:{type:"number",defaultValue:50}},func:"turtleSetWheelTo",blockCategory:"motion"},{opcode:"turtleFollowLine",text:"[COLOR] \uc120\uc744 \ub530\ub77c\uac00\uae30",blockType:"command",arguments:{COLOR:{type:"string",menu:"line_color",defaultValue:"black"}},func:"turtleFollowLine",blockCategory:"motion"},{opcode:"turtleFollowLineUntil",text:"\uac80\uc740\uc0c9 \uc120\uc744 \ub530\ub77c [COLOR]\uae4c\uc9c0 \uc774\ub3d9\ud558\uae30",
blockType:"command",arguments:{COLOR:{type:"string",menu:"target_color",defaultValue:"red"}},func:"turtleFollowLineUntil",blockCategory:"motion"},{opcode:"turtleFollowLineUntilBlack",text:"[COLOR] \uc120\uc744 \ub530\ub77c \uac80\uc740\uc0c9\uae4c\uc9c0 \uc774\ub3d9\ud558\uae30",blockType:"command",arguments:{COLOR:{type:"string",menu:"color_line",defaultValue:"red"}},func:"turtleFollowLineUntilBlack",blockCategory:"motion"},{opcode:"turtleCrossIntersection",text:"\uac80\uc740\uc0c9 \uad50\ucc28\ub85c \uac74\ub108\uac00\uae30",
blockType:"command",func:"turtleCrossIntersection",blockCategory:"motion"},{opcode:"turtleTurnAtIntersection",text:"\uac80\uc740\uc0c9 \uad50\ucc28\ub85c\uc5d0\uc11c [DIRECTION]\uc73c\ub85c \ub3cc\uae30",blockType:"command",arguments:{DIRECTION:{type:"string",menu:"left_right_back",defaultValue:"left"}},func:"turtleTurnAtIntersection",blockCategory:"motion"},{opcode:"turtleSetFollowingSpeedTo",text:"\uc120 \ub530\ub77c\uac00\uae30 \uc18d\ub3c4\ub97c [SPEED](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",
arguments:{SPEED:{type:"string",menu:"speed",defaultValue:"5"}},func:"turtleSetFollowingSpeedTo",blockCategory:"motion"},{opcode:"turtleStop",text:"\uc815\uc9c0\ud558\uae30",blockType:"command",func:"turtleStop",blockCategory:"motion"},"---",{opcode:"turtleSetHeadLedTo",text:"\uba38\ub9ac LED\ub97c [COLOR]\uc73c\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{COLOR:{type:"string",menu:"led_color",defaultValue:"red"}},func:"turtleSetHeadLedTo",blockCategory:"looks"},{opcode:"turtleSetHeadLedToPicker",
text:"\uba38\ub9ac LED\ub97c [COLOR]\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{COLOR:{type:"color",defaultValue:"#ff0000"}},func:"turtleSetHeadLedToPicker",blockCategory:"looks"},{opcode:"turtleChangeHeadLedByRGB",text:"\uba38\ub9ac LED\ub97c R: [RED] G: [GREEN] B: [BLUE]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{RED:{type:"number",defaultValue:10},GREEN:{type:"number",defaultValue:0},BLUE:{type:"number",defaultValue:0}},func:"turtleChangeHeadLedByRGB",blockCategory:"looks"},
{opcode:"turtleSetHeadLedToRGB",text:"\uba38\ub9ac LED\ub97c R: [RED] G: [GREEN] B: [BLUE](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{RED:{type:"number",defaultValue:255},GREEN:{type:"number",defaultValue:0},BLUE:{type:"number",defaultValue:0}},func:"turtleSetHeadLedToRGB",blockCategory:"looks"},{opcode:"turtleClearHeadLed",text:"\uba38\ub9ac LED \ub044\uae30",blockType:"command",func:"turtleClearHeadLed",blockCategory:"looks"},"---",{opcode:"turtlePlaySoundTimes",text:"[SOUND] \uc18c\ub9ac [REPEAT]\ubc88 \uc7ac\uc0dd\ud558\uae30",
blockType:"command",arguments:{SOUND:{type:"string",menu:"sound",defaultValue:"beep"},REPEAT:{type:"number",defaultValue:1}},func:"turtlePlaySoundTimes",blockCategory:"sound"},{opcode:"turtlePlaySoundTimesUntilDone",text:"[SOUND] \uc18c\ub9ac [REPEAT]\ubc88 \uc7ac\uc0dd\ud558\uace0 \uae30\ub2e4\ub9ac\uae30",blockType:"command",arguments:{SOUND:{type:"string",menu:"sound",defaultValue:"beep"},REPEAT:{type:"number",defaultValue:1}},func:"turtlePlaySoundTimesUntilDone",blockCategory:"sound"},{opcode:"turtleChangeBuzzerBy",
text:"\ubc84\uc800 \uc74c\uc744 [HZ]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{HZ:{type:"number",defaultValue:10}},func:"turtleChangeBuzzerBy",blockCategory:"sound"},{opcode:"turtleSetBuzzerTo",text:"\ubc84\uc800 \uc74c\uc744 [HZ](\uc73c)\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{HZ:{type:"number",defaultValue:1E3}},func:"turtleSetBuzzerTo",blockCategory:"sound"},{opcode:"turtleClearSound",text:"\uc18c\ub9ac \ub044\uae30",blockType:"command",func:"turtleClearSound",
blockCategory:"sound"},{opcode:"turtlePlayNote",text:"[NOTE][OCTAVE] \uc74c\uc744 \uc5f0\uc8fc\ud558\uae30",blockType:"command",arguments:{NOTE:{type:"string",menu:"note",defaultValue:"C"},OCTAVE:{type:"string",menu:"octave",defaultValue:"4"}},func:"turtlePlayNote",blockCategory:"sound"},{opcode:"turtlePlayNoteForBeats",text:"[NOTE][OCTAVE] \uc74c\uc744 [BEAT]\ubc15\uc790 \uc5f0\uc8fc\ud558\uae30",blockType:"command",arguments:{NOTE:{type:"string",menu:"note",defaultValue:"C"},OCTAVE:{type:"string",
menu:"octave",defaultValue:"4"},BEAT:{type:"number",defaultValue:.5}},func:"turtlePlayNoteForBeats",blockCategory:"sound"},{opcode:"turtleRestForBeats",text:"[BEAT]\ubc15\uc790 \uc26c\uae30",blockType:"command",arguments:{BEAT:{type:"number",defaultValue:.25}},func:"turtleRestForBeats",blockCategory:"sound"},{opcode:"turtleChangeTempoBy",text:"\uc5f0\uc8fc \uc18d\ub3c4\ub97c [BPM]\ub9cc\ud07c \ubc14\uafb8\uae30",blockType:"command",arguments:{BPM:{type:"number",defaultValue:20}},func:"turtleChangeTempoBy",
blockCategory:"sound"},{opcode:"turtleSetTempoTo",text:"\uc5f0\uc8fc \uc18d\ub3c4\ub97c [BPM]BPM\uc73c\ub85c \uc815\ud558\uae30",blockType:"command",arguments:{BPM:{type:"number",defaultValue:60}},func:"turtleSetTempoTo",blockCategory:"sound"},"---",{opcode:"turtleColorNumber",text:"\uc0c9\uae54 \ubc88\ud638",blockType:"reporter",func:"turtleColorNumber",blockCategory:"sensing"},{opcode:"turtleColorPattern",text:"\uc0c9\uae54 \ud328\ud134",blockType:"reporter",func:"turtleColorPattern",blockCategory:"sensing"},
{opcode:"turtleFloor",text:"\ubc14\ub2e5 \uc13c\uc11c",blockType:"reporter",func:"turtleFloor",blockCategory:"sensing"},{opcode:"turtleButton",text:"\ubc84\ud2bc",blockType:"reporter",func:"turtleButton",blockCategory:"sensing"},{opcode:"turtleAccelerationX",text:"x\ucd95 \uac00\uc18d\ub3c4",blockType:"reporter",func:"turtleAccelerationX",blockCategory:"sensing"},{opcode:"turtleAccelerationY",text:"y\ucd95 \uac00\uc18d\ub3c4",blockType:"reporter",func:"turtleAccelerationY",blockCategory:"sensing"},
{opcode:"turtleAccelerationZ",text:"z\ucd95 \uac00\uc18d\ub3c4",blockType:"reporter",func:"turtleAccelerationZ",blockCategory:"sensing"},{opcode:"turtleWhenColorTouched",text:"[COLOR]\uc5d0 \ub2ff\uc558\uc744 \ub54c",blockType:"hat",arguments:{COLOR:{type:"string",menu:"touching_color",defaultValue:"red"}},func:"turtleWhenColorTouched",blockCategory:"sensing"},{opcode:"turtleWhenColorPattern",text:"\uc0c9\uae54 \ud328\ud134\uc774 [COLOR1][COLOR2]\uc77c \ub54c",blockType:"hat",arguments:{COLOR1:{type:"string",
menu:"pattern_color",defaultValue:"red"},COLOR2:{type:"string",menu:"pattern_color",defaultValue:"yellow"}},func:"turtleWhenColorPattern",blockCategory:"sensing"},{opcode:"turtleWhenButtonState",text:"\ubc84\ud2bc\uc744 [EVENT] \ub54c",blockType:"hat",arguments:{EVENT:{type:"string",menu:"when_button_state",defaultValue:"clicked"}},func:"turtleWhenButtonState",blockCategory:"sensing"},{opcode:"turtleWhenTilt",text:"[TILT] \ub54c",blockType:"hat",arguments:{TILT:{type:"string",menu:"when_tilt",defaultValue:"tilt forward"}},
func:"turtleWhenTilt",blockCategory:"sensing"},{opcode:"turtleTouchingColor",text:"[COLOR]\uc5d0 \ub2ff\uc558\ub294\uac00?",blockType:"Boolean",arguments:{COLOR:{type:"string",menu:"touching_color",defaultValue:"red"}},func:"turtleTouchingColor",blockCategory:"sensing"},{opcode:"turtleIsColorPattern",text:"\uc0c9\uae54 \ud328\ud134\uc774 [COLOR1][COLOR2]\uc778\uac00?",blockType:"Boolean",arguments:{COLOR1:{type:"string",menu:"pattern_color",defaultValue:"red"},COLOR2:{type:"string",menu:"pattern_color",
defaultValue:"yellow"}},func:"turtleIsColorPattern",blockCategory:"sensing"},{opcode:"turtleButtonState",text:"\ubc84\ud2bc\uc744 [EVENT]?",blockType:"Boolean",arguments:{EVENT:{type:"string",menu:"button_state",defaultValue:"clicked"}},func:"turtleButtonState",blockCategory:"sensing"},{opcode:"turtleTilt",text:"[TILT]?",blockType:"Boolean",arguments:{TILT:{type:"string",menu:"tilt",defaultValue:"tilt forward"}},func:"turtleTilt",blockCategory:"sensing"},{opcode:"turtleBattery",text:"\ubc30\ud130\ub9ac [BATTERY]?",
blockType:"Boolean",arguments:{BATTERY:{type:"string",menu:"battery",defaultValue:"normal"}},func:"turtleBattery",blockCategory:"sensing"}],menus:{move_unit:[{text:"cm",value:"cm"},{text:"\ucd08",value:"seconds"},{text:"\ud384\uc2a4",value:"pulses"}],turn_unit:[{text:"\ub3c4",value:"degrees"},{text:"\ucd08",value:"seconds"},{text:"\ud384\uc2a4",value:"pulses"}],cm_sec:[{text:"cm",value:"cm"},{text:"\ucd08",value:"seconds"}],deg_sec:[{text:"\ub3c4",value:"degrees"},{text:"\ucd08",value:"seconds"}],
head_tail:[{text:"\uba38\ub9ac",value:"head"},{text:"\uaf2c\ub9ac",value:"tail"}],left_right:[{text:"\uc67c\ucabd",value:"left"},{text:"\uc624\ub978\ucabd",value:"right"}],left_right_both:[{text:"\uc67c\ucabd",value:"left"},{text:"\uc624\ub978\ucabd",value:"right"},{text:"\uc591\ucabd",value:"both"}],left_right_back:[{text:"\uc67c\ucabd",value:"left"},{text:"\uc624\ub978\ucabd",value:"right"},{text:"\ub4a4\ucabd",value:"back"}],line_color:[{text:"\uac80\uc740\uc0c9",value:"black"},{text:"\ube68\uac04\uc0c9",
value:"red"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\uc544\ubb34 \uc0c9",value:"any color"}],target_color:[{text:"\ube68\uac04\uc0c9",value:"red"},{text:"\ub178\ub780\uc0c9",value:"yellow"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud558\ub298\uc0c9",value:"sky blue"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\uc790\uc8fc\uc0c9",value:"purple"},{text:"\uc544\ubb34 \uc0c9",value:"any color"}],color_line:[{text:"\ube68\uac04\uc0c9",value:"red"},
{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\uc544\ubb34 \uc0c9",value:"any color"}],touching_color:[{text:"\ube68\uac04\uc0c9",value:"red"},{text:"\uc8fc\ud669\uc0c9",value:"orange"},{text:"\ub178\ub780\uc0c9",value:"yellow"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud558\ub298\uc0c9",value:"sky blue"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\uc790\uc8fc\uc0c9",value:"purple"},{text:"\uac80\uc740\uc0c9",value:"black"},{text:"\ud558\uc580\uc0c9",
value:"white"}],pattern_color:[{text:"\ube68\uac04\uc0c9",value:"red"},{text:"\ub178\ub780\uc0c9",value:"yellow"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud558\ub298\uc0c9",value:"sky blue"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\uc790\uc8fc\uc0c9",value:"purple"}],speed:[{text:"1",value:"1"},{text:"2",value:"2"},{text:"3",value:"3"},{text:"4",value:"4"},{text:"5",value:"5"},{text:"6",value:"6"},{text:"7",value:"7"},{text:"8",value:"8"}],led_color:[{text:"\ube68\uac04\uc0c9",value:"red"},
{text:"\uc8fc\ud669\uc0c9",value:"orange"},{text:"\ub178\ub780\uc0c9",value:"yellow"},{text:"\ucd08\ub85d\uc0c9",value:"green"},{text:"\ud558\ub298\uc0c9",value:"sky blue"},{text:"\ud30c\ub780\uc0c9",value:"blue"},{text:"\ubcf4\ub77c\uc0c9",value:"violet"},{text:"\uc790\uc8fc\uc0c9",value:"purple"},{text:"\ud558\uc580\uc0c9",value:"white"}],sound:[{text:"\uc090",value:"beep"},{text:"\ubb34\uc791\uc704 \uc090",value:"random beep"},{text:"\uc0ac\uc774\ub80c",value:"siren"},{text:"\uc5d4\uc9c4",value:"engine"},
{text:"\ub85c\ubd07",value:"robot"},{text:"\ud589\uc9c4",value:"march"},{text:"\uc0dd\uc77c",value:"birthday"},{text:"\ub514\ube44\ub514\ube44\ub525",value:"dibidibidip"},{text:"\uc798 \ud588\uc5b4\uc694",value:"good job"}],note:[{text:"\ub3c4",value:"C"},{text:"\ub3c4\u266f (\ub808\u266d)",value:"C\u266f (D\u266d)"},{text:"\ub808",value:"D"},{text:"\ub808\u266f (\ubbf8\u266d)",value:"D\u266f (E\u266d)"},{text:"\ubbf8",value:"E"},{text:"\ud30c",value:"F"},{text:"\ud30c\u266f (\uc194\u266d)",value:"F\u266f (G\u266d)"},
{text:"\uc194",value:"G"},{text:"\uc194\u266f (\ub77c\u266d)",value:"G\u266f (A\u266d)"},{text:"\ub77c",value:"A"},{text:"\ub77c\u266f (\uc2dc\u266d)",value:"A\u266f (B\u266d)"},{text:"\uc2dc",value:"B"}],octave:[{text:"1",value:"1"},{text:"2",value:"2"},{text:"3",value:"3"},{text:"4",value:"4"},{text:"5",value:"5"},{text:"6",value:"6"},{text:"7",value:"7"}],when_button_state:[{text:"\ud074\ub9ad\ud588\uc744",value:"clicked"},{text:"\ub354\ube14\ud074\ub9ad\ud588\uc744",value:"double-clicked"},{text:"\uae38\uac8c~\ub20c\ub800\uc744",
value:"long-pressed"}],when_tilt:[{text:"\uc55e\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt forward"},{text:"\ub4a4\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt backward"},{text:"\uc67c\ucabd\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt left"},{text:"\uc624\ub978\ucabd\uc73c\ub85c \uae30\uc6b8\uc600\uc744",value:"tilt right"},{text:"\uac70\uafb8\ub85c \ub4a4\uc9d1\uc5c8\uc744",value:"tilt flip"},{text:"\uae30\uc6b8\uc774\uc9c0 \uc54a\uc558\uc744",value:"not tilt"}],button_state:[{text:"\ud074\ub9ad\ud588\ub294\uac00",
value:"clicked"},{text:"\ub354\ube14\ud074\ub9ad\ud588\ub294\uac00",value:"double-clicked"},{text:"\uae38\uac8c~\ub20c\ub800\ub294\uac00",value:"long-pressed"}],tilt:[{text:"\uc55e\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt forward"},{text:"\ub4a4\ub85c \uae30\uc6b8\uc784",value:"tilt backward"},{text:"\uc67c\ucabd\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt left"},{text:"\uc624\ub978\ucabd\uc73c\ub85c \uae30\uc6b8\uc784",value:"tilt right"},{text:"\uac70\uafb8\ub85c \ub4a4\uc9d1\uc74c",value:"tilt flip"},
{text:"\uae30\uc6b8\uc774\uc9c0 \uc54a\uc74c",value:"not tilt"}],battery:[{text:"\uc815\uc0c1",value:"normal"},{text:"\ubd80\uc871",value:"low"},{text:"\uc5c6\uc74c",value:"empty"}]}}};TurtleExtension.prototype.getRobot=function(a){if(void 0===a.INDEX){if(this.runtime.roboidRunner)return this.runtime.roboidRunner.getRobot("turtle",0)}else if(a=RoboidUtil.toNumber(a.INDEX,-1),0<=a&&this.runtime.roboidRunner)return this.runtime.roboidRunner.getRobot("turtle",a)};
TurtleExtension.prototype.turtleMoveForward=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveForward(c)})};TurtleExtension.prototype.turtleMoveBackward=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveBackward(c)})};TurtleExtension.prototype.turtleTurn=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.turn(a.DIRECTION,c)})};
TurtleExtension.prototype.turtleMoveForwardUnit=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveForwardUnit(a.VALUE,a.UNIT,c)})};TurtleExtension.prototype.turtleMoveBackwardUnit=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.moveBackwardUnit(a.VALUE,a.UNIT,c)})};TurtleExtension.prototype.turtleTurnUnitInPlace=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.turnUnit(a.DIRECTION,a.VALUE,a.UNIT,c)})};
TurtleExtension.prototype.turtlePivotAroundWheelUnitInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.pivotUnit(a.WHEEL,a.VALUE,a.UNIT,a.TOWARD,c)})};TurtleExtension.prototype.turtleTurnUnitWithRadiusInDirection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.swingUnit(a.DIRECTION,a.VALUE,a.UNIT,a.RADIUS,a.TOWARD,c)})};
TurtleExtension.prototype.turtleChangeWheelsByLeftRight=function(a){var b=this.getRobot(a);b&&b.changeWheels(a.LEFT,a.RIGHT)};TurtleExtension.prototype.turtleSetWheelsToLeftRight=function(a){var b=this.getRobot(a);b&&b.setWheels(a.LEFT,a.RIGHT)};TurtleExtension.prototype.turtleChangeWheelBy=function(a){var b=this.getRobot(a);b&&b.changeWheel(a.WHEEL,a.VALUE)};TurtleExtension.prototype.turtleSetWheelTo=function(a){var b=this.getRobot(a);b&&b.setWheel(a.WHEEL,a.VALUE)};
TurtleExtension.prototype.turtleFollowLine=function(a){var b=this.getRobot(a);b&&b.followLine(a.COLOR)};TurtleExtension.prototype.turtleFollowLineUntil=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.followLineUntil(a.COLOR,c)})};TurtleExtension.prototype.turtleFollowLineUntilBlack=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.followLineUntilBlack(a.COLOR,c)})};
TurtleExtension.prototype.turtleCrossIntersection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.crossIntersection(c)})};TurtleExtension.prototype.turtleTurnAtIntersection=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.turnAtIntersection(a.DIRECTION,c)})};TurtleExtension.prototype.turtleSetFollowingSpeedTo=function(a){var b=this.getRobot(a);b&&b.setLineTracerSpeed(a.SPEED)};
TurtleExtension.prototype.turtleStop=function(a){(a=this.getRobot(a))&&a.stop()};TurtleExtension.prototype.turtleSetHeadLedTo=function(a){var b=this.getRobot(a);b&&b.setHeadColor(a.COLOR)};TurtleExtension.prototype.turtleSetHeadLedToPicker=function(a){var b=this.getRobot(a);b&&b.setHeadRgbArray(RoboidUtil.toRgbArray(a.COLOR))};TurtleExtension.prototype.turtleChangeHeadLedByRGB=function(a){var b=this.getRobot(a);b&&b.changeHeadRgb(a.RED,a.GREEN,a.BLUE)};
TurtleExtension.prototype.turtleSetHeadLedToRGB=function(a){var b=this.getRobot(a);b&&b.setHeadRgb(a.RED,a.GREEN,a.BLUE)};TurtleExtension.prototype.turtleClearHeadLed=function(a){(a=this.getRobot(a))&&a.clearHead()};TurtleExtension.prototype.turtlePlaySound=function(a){var b=this.getRobot(a);b&&b.playSound(a.SOUND,1)};TurtleExtension.prototype.turtlePlaySoundTimes=function(a){var b=this.getRobot(a);b&&b.playSound(a.SOUND,a.REPEAT)};
TurtleExtension.prototype.turtlePlaySoundTimesUntilDone=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.playSoundUntil(a.SOUND,a.REPEAT,c)})};TurtleExtension.prototype.turtleChangeBuzzerBy=function(a){var b=this.getRobot(a);b&&b.changeBuzzer(a.HZ)};TurtleExtension.prototype.turtleSetBuzzerTo=function(a){var b=this.getRobot(a);b&&b.setBuzzer(a.HZ)};TurtleExtension.prototype.turtleClearSound=function(a){(a=this.getRobot(a))&&a.clearSound()};
TurtleExtension.prototype.turtlePlayNote=function(a){var b=this.getRobot(a);b&&b.playNote(a.NOTE,a.OCTAVE)};TurtleExtension.prototype.turtlePlayNoteForBeats=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.playNoteBeat(a.NOTE,a.OCTAVE,a.BEAT,c)})};TurtleExtension.prototype.turtleRestForBeats=function(a){var b=this;return new Promise(function(c){var d=b.getRobot(a);d&&d.restBeat(a.BEAT,c)})};
TurtleExtension.prototype.turtleChangeTempoBy=function(a){var b=this.getRobot(a);b&&b.changeTempo(a.BPM)};TurtleExtension.prototype.turtleSetTempoTo=function(a){var b=this.getRobot(a);b&&b.setTempo(a.BPM)};TurtleExtension.prototype.turtleColorNumber=function(a){return(a=this.getRobot(a))?a.getColorNumber():-1};TurtleExtension.prototype.turtleColorPattern=function(a){return(a=this.getRobot(a))?a.getColorPattern():-1};
TurtleExtension.prototype.turtleFloor=function(a){return(a=this.getRobot(a))?a.getFloor():0};TurtleExtension.prototype.turtleButton=function(a){return(a=this.getRobot(a))?a.getButton():0};TurtleExtension.prototype.turtleAccelerationX=function(a){return(a=this.getRobot(a))?a.getAccelerationX():0};TurtleExtension.prototype.turtleAccelerationY=function(a){return(a=this.getRobot(a))?a.getAccelerationY():0};
TurtleExtension.prototype.turtleAccelerationZ=function(a){return(a=this.getRobot(a))?a.getAccelerationZ():0};TurtleExtension.prototype.turtleWhenColorTouched=function(a){var b=this.getRobot(a);return b?b.checkTouchingColor(a.COLOR):!1};TurtleExtension.prototype.turtleWhenColorPattern=function(a){var b=this.getRobot(a);return b?b.checkColorPattern(a.COLOR1,a.COLOR2):!1};TurtleExtension.prototype.turtleWhenButtonState=function(a){var b=this.getRobot(a);return b?b.checkButtonEvent(a.EVENT):!1};
TurtleExtension.prototype.turtleWhenTilt=function(a){var b=this.getRobot(a);return b?b.checkTilt(a.TILT):!1};TurtleExtension.prototype.turtleTouchingColor=function(a){var b=this.getRobot(a);return b?b.checkTouchingColor(a.COLOR):!1};TurtleExtension.prototype.turtleIsColorPattern=function(a){var b=this.getRobot(a);return b?b.checkColorPattern(a.COLOR1,a.COLOR2):!1};TurtleExtension.prototype.turtleButtonState=function(a){var b=this.getRobot(a);return b?b.checkButtonEvent(a.EVENT):!1};
TurtleExtension.prototype.turtleTilt=function(a){var b=this.getRobot(a);return b?b.checkTilt(a.TILT):!1};TurtleExtension.prototype.turtleBattery=function(a){var b=this.getRobot(a);return b?b.checkBattery(a.BATTERY):!1};Date.now||(Date.now=function(){return(new Date).getTime()});module.exports=TurtleExtension;